### ISSUE TITLE
[feat] Entity add : TouristSpot, Trail, Festival

### ISSUE THREAD

**Issue by Federico-15** [DIVE-2024/Donghae_zip#1]
## 🚀 Description
Entity add

## ✅ TODO
- [x] : TouristSpot(여행지) Entity add
- [x] : Trail(둘렛길) Entity add
- [x] : Festival(축제) Entity add

**Comment by fosu-mensah** [comment]
테스트
