### ISSUE TITLE
[feat] Entity add : 동해선,숙박,식당,KaKao Api 활용

### ISSUE THREAD

**Issue by Federico-15** [DIVE-2024/Donghae_zip#2]
## 🚀 Description
동해선, 숙박, 식당 엔티티 추가후 테스트까지.

## ✅ TODO
- [x] : 동해선 엔티티 추가
- [x] : 숙박 엔티티 추가
- [x] : 식당 엔티티 추가
- [x] : Postman,Swagger get 매서드 test
- [x] : Kakao Map Api를 활용하여 주소를 경위도로 변환하는 작업
