### ISSUE TITLE
[ui/feature]메인페이지 Map띄우기 및 전체 스타일 변환

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#49]
## 🚀 Description
ui 최적화, 기능 추가 고안

## ✅ TODO
- [x] : Main Page Map 띄우기
- [x] : ui 스타일 변환
- [ ] : 기능추가-> 카테고리별 검색
