### ISSUE TITLE
[feature/ui] 회원 이미지설정 (fix) -> 좋아요로직

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#56]
## 🚀 Description
ui 개선, 좋아요 로직 구현, 회원 이미지

## ✅ TODO
- [ ] : 각 회원 대표하는 이미지 설정
- [x] : 좋아요 구현 (api 로직 수정, 연결) -> 현재 카테고리 전부 구현( -> 아직 회원이 자신이 누른 좋아요 목록 페이지 구현 x)
- [x] : ui 확장 개선 (구조 개편, 뒤로가기 버튼 생성,좋아요 버튼 스타일 개선)
- [x] : code Refactoring -> 각 카테고리 디테일페이지 코드 리팩토링 완
