### ISSUE TITLE
[feat/ui] 사용자별 마이페이지 구현

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#59]
## 🚀 Description
사용자별 마이페이지 구현

## ✅ TODO
- [ ] : 사용자별 마이페이지 구현 -> 내일 구현해보겠습니다. 일단 오늘 dev로 올림
- [x] : 전체 ui 개선 -> (소숫점 별점 구현, 카테고리별 List구조)
- [x] : 각 카테고리 평균 리뷰 점수 구현
