### ISSUE TITLE
[feat/ui] 캘린더 api와 날씨 api 가져와 사용자맞춤 캘린더 초안구성

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#63]
## 🚀 Description
캘린더 api 가져와 사용자 추천 여행지 보이게 구현

## ✅ TODO
- [x] : 캘린더 api 가져와 동해 출동해 페이지에 적용
- [x] : 캘린더 선택 -> 당일, 1박2일, 2박3일 까지 선택
- [x] : 날씨 api 가져오기 => (처음에 한번 데이터 가져오고 -> 부산,울산의 향후 5일의 날씨데이터를 3번씩 끊어서 가져옴)
- [x] : 날씨 api를 통해 사용자가 정한날에 대한 부산,울산의 날씨 제공 -> 어느정도의 기능 구현 완
