### ISSUE TITLE
[feat/ui] 동해 출동해 사용자에게 맞춤 여행지 보여주는 기능 구현

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#65]
## 🚀 Description
동해 출동해 사용자에게 맞춤 여행지 보여주는 기능 구현
daily commit을 목표로 프젝 진행 -> 현재 프론트 쪽 기능위주로만 만듬-> 앞으로 DB 일정 테이블 구성(여행지, 숙박, 식당의 id통해 구성되게)
일단 추천 기능은 후순위로 구현 -> 우선, 일정을 구성하는 기능을 먼저 구현하는게 맞음.

## ✅ TODO

- [x] : 여행지 선택 페이지 구현
- [ ] : 날씨에 따라 추천 
- [x] : 시간대별로 일정 짜게 구현
- [ ] : 우선 전체 카테고리에서 일정에 집어넣는 로직부터 구현.
