### ISSUE TITLE
[feat/ui] 동해선 여행일정 페이지 구성

### ISSUE THREAD

**Issue by R7-Cristiano** [DIVE-2024/Donghae_zip#67]
## 🚀 Description
동해선 여행일정 페이지 구성

## ✅ TODO
- [x] : [Backend] Travel,TravelDetail( 일정 목록, 일정 상세) 엔티티 생성
- [x] : [Frontend] 여행일정 목록페이지 구성 (1-4페이지로 구성) 1. 여행지목록 -> 2. 일정정하기 -> 3.일별 여행지 구성 -> 4. 일정 완성 페이지
- [ ] : 자세한 동선 로직은 후에 구성-> 아이디어만 구성해서 노션에 업로드
